repos:
  - repo: local
    hooks:
      - id: doctoc-docker
        name: doctoc via Docker
        entry: bash -c 'docker run --rm -v "$(pwd)":/app -w /app node:20 npx doctoc README.md --maxlevel 3 --notitle'
        language: system
        types: [markdown]
        files: ^README\.md$

      - id: prettier-docker
        name: Prettier via Docker
        entry: bash -c 'docker run --rm -v "$(pwd)":/app -w /app node:20 npx prettier --write .'
        language: system
        types: [markdown]
        files: \.md$
        pass_filenames: false
